name: Astra Sheepdog Centre
favicon: null
layout_spectrum: 0.80484
typography_spectrum: 0.24108
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d1a08'
    - '#d7cbb1'
    - '#77a038'
    - '#244400'
    - '#606545'
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
