name: Astra Sheepdog Centre
favicon: null
layout_spectrum: 0.49715170729905367
typography_spectrum: 0.7013971377164125
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.11730628041550517
  lightness: 0.009409585501998663
  saturation: 0.5037202453240752
  rhythmicContrast: 0.8557613489683717
purpose: []
